apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme-issuer
spec:
  acme:
    email: bmaisonti@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: example-issuer-account-key
    solvers:
      - dns01:
          cloudflare:
            email: bmaisonti@gmail.com
            apiKeySecretRef:
              name: cloudflare-api-key-secret
              key: api-key
